jobs:  
  include:
    - stage: test
      name: iOS
      os: osx
      language: objective-c
      osx_image: xcode11.4
      script: xcodebuild clean test -project DictionaryDecoder.xcodeproj -scheme DictionaryDecoder -sdk iphonesimulator13.4 -destination "name=iPhone 11"
    - stage: test
      name: macOS
      os: osx
      language: objective-c
      osx_image: xcode11.4
      script: xcodebuild clean test -project DictionaryDecoder.xcodeproj -scheme DictionaryDecoder-macOS -sdk macosx
      after_success: bash <(curl -s https://codecov.io/bash) -J 'DictionaryDecoder'
    - stage: test
      name: Swift PM
      osx_image: xcode11.4
      script: swift package clean; swift test
    - stage: test
      name: Swift Linux
      language: ruby
      os: linux
      dist: trusty
      services: docker
      script:
          - docker pull swift
          - docker run -it --mount src="$(pwd)",target=/swift_source,type=bind swift /bin/sh -c "cd swift_source; swift package clean; swift test"